### ISSUE TITLE
MDX support

### ISSUE THREAD

**Issue by mikemajara** [kingsdesigntas/gatsby-chakra-starter#1]
I can't see any MDX files around and when cloning style does not work on these out of the box. Did you manage to get them working?

I can also see that chakra is not included as a plugin in `gatsby-config.js` is that really not needed?

**Comment by jessebenjamin1** [comment]
Hey @mikemajara, thanks for checking out our starter! Everything was already setup to support mdx - gatsby-plugin-mdx is in the gatsby-config, which has a default layout and remark images set up too.

I've just gone and added an example mdx page with /about as the slug. You can find it under src/pages/about.mdx. Leet us know if you run into any trouble 😄
